# Staging values for ingestion.
nameOverride: ingestion
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "info"
    reason: "new staging deploy"
    ingress:
      class: "nginx-staging"
    current: true
    resources:
      requests:
        cpu: 150m
        memory: 600Mi
      limits:
        cpu: 300m
        memory: 800Mi
    autoscaling:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
