# Production values for package.
nameOverride: package
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    log:
      level: "error"
    reason: "new prod deploy"
    ingress:
      class: "nginx-prod"
    resources:
      requests:
        cpu: 90m
        memory: 100Mi
      limits:
        cpu: 180m
        memory: 140Mi
    autoscaling:
      enabled: true
      maxReplicas: 50
      minReplicas: 1
      targetCPUUtilizationPercentage: 50
